en:
  languageName: English
  weight: 1
  contentDir: content/en
  params:
    dateFormat: "January 2, 2006"
 
ru:
  languageName: Русский
  weight: 2
  contentDir: content/ru
  params:
    dateFormat: "January 2, 2006"
  
  menu:
    main:
      - name: Биография
        url: /
        weight: 10
      - name: Статьи
        url: /#papers
        weight: 11
      - name: Переговоры
        url: /#talks
        weight: 12
      - name: Новости
        url: /#news
        weight: 13
      - name: Опыт
        url: experience/
        weight: 20
      - name: Проекты
        url: projects/
        weight: 30
      - name: Преподавание
        url: teaching/
        weight: 40
