en:
  languageName: English
  weight: 2
  contentDir: content/en
  params:
    dateFormat: "January 2, 2006"
    
  menu:
    main:
      - name: Bio
        url: en/
        weight: 10
      - name: Papers
        url: en/#papers
        weight: 11
      - name: Talks
        url: en/#talks
        weight: 12
      - name: News
        url: en/#news
        weight: 13
      - name: Experience
        url: en/experience/
        weight: 20
      - name: Projects
        url: en/projects/
        weight: 30
      - name: Teaching
        url: en/teaching/
        weight: 40
 
ru:
  languageName: Русский
  weight: 2
  contentDir: content/ru
  params:
    dateFormat: "January 2, 2006"
  
  menu:
    main:
      - name: Биография
        url: ru/
        weight: 10
      - name: Статьи
        url: ru/#papers
        weight: 11
      - name: Переговоры
        url: ru/#talks
        weight: 12
      - name: Новости
        url: ru/#news
        weight: 13
      - name: Опыт
        url: ru/experience/
        weight: 20
      - name: Проекты
        url: ru/projects/
        weight: 30
      - name: Преподавание
        url: ru/teaching/
        weight: 40
